### ISSUE TITLE
Mention Box

### ISSUE THREAD

**Issue by theofidry** [paragonie/pharaoh#10]
Not sure how you feel about that since I guess pharaoh was thought as a standalone tool I suppose. But [Box](https://github.com/humbug/box) ships pharaoh as  a [`diff` command](https://github.com/humbug/box/blob/master/src/Console/Command/Diff.php).

Since if one is interested in having a diff between PHARs she/he may be interested as well in other PHAR related utilities, it may be worth mentioning Box.

I'd be happy to increase the visibility of that project via Box as well, maybe a message when running `box diff` to say that it is provided by Pharaoh, not sure which form would be the best

**Comment by paragonie-scott** [comment]
No objections here. I'll revisit this as soon as I have a bit more time to spare.

**Comment by paragonie-scott** [comment]
This is in the README.

**Comment by theofidry** [comment]
Cheers
