### ISSUE TITLE
world writable dir

### ISSUE THREAD

**Issue by glensc** [paragonie/pharaoh#3]
https://github.com/paragonie/pharaoh/blob/be048c1d5150a3a8a60fe6f46e7cdbfadb9c94f7/src/Pharaoh/Pharaoh.php#L39

no comments

**Comment by paragonie-security** [comment]
Typically everything in `/tmp` is very permissive, but Pharaoh will work with 0700, so we should do that. Thanks for bringing this to our attention.

**Comment by kelunik** [comment]
@paragonie-scott That's not true. `/tmp` itself is very permissive, but not the content within it.

**Comment by paragonie-scott** [comment]
This will be fixed in `v0.3.0`.

**Comment by glensc** [comment]
cross referencing commit and issue
https://github.com/paragonie/pharaoh/commit/c13552da28c0a09e24e07e16101ea13f8a381573

**Comment by glensc** [comment]
altho i do not see why you not use `0700` permission. your're the only consumer of that directory, why you want to share that dir content with anything else?

https://github.com/paragonie/pharaoh/blob/c13552da28c0a09e24e07e16101ea13f8a381573/src/Pharaoh/Pharaoh.php#L59

altho i think php rfc should be filed to make secure directory, so such security related errors won't be made by inexperienced users.
