### ISSUE TITLE
The compared phars are altered

### ISSUE THREAD

**Issue by theofidry** [paragonie/pharaoh#6]
When executing a diff between two PHAR files, their contents are altered. This can be seen with [Box](https://github.com/humbug/box) for example:

```
$ git@github.com:humbug/box.git && cd box
$ composer install
$ bin/phpunit tests/Console/Command/DiffTest.php
$ git st
On branch acme/foo
Your branch is up to date with 'upstream/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   fixtures/diff/simple-phar-bar.phar
	modified:   fixtures/diff/simple-phar-foo.phar
```

The issue seems to come from [setting the alias](https://github.com/paragonie/pharaoh/blob/master/src/Pharaoh/Pharaoh.php#L56) which alters the original PHAR.

I'm not sure why setting the alias is necessary, but restoring the alias after usage does not seem to help, so maybe Pharaoh should manipulate a copied PHAR instead.

**Comment by paragonie-scott** [comment]
> I'm not sure why setting the alias is necessary

Try opening two identical PHP archives with the same filename (and thus, the same alias) from different directories.

**Comment by theofidry** [comment]
I see, so maybe we should copy the PHARs before comparing them?

**Comment by theofidry** [comment]
@paragonie-scott what's your opinion here? Willing to go that way or you would prefer tackling the issue from another angle?

**Comment by paragonie-scott** [comment]
I don't really have any strong opinions on the best way forward.

If you think copying the PHARs before comparing them will solve the problem, please feel free to give it a shot. I just recall having two PHARs with the same alias (which IIRC defaults to the filename) caused a conflict issue.

**Comment by theofidry** [comment]
The problem persist indeed, but this means two _identical_ PHARs will always show as different (because the alias, hence the signature, will differ).

I've decided to not compare the signatures & aliases in Box since I really don't know how to handle this either.
